import { MigrationInterface, QueryRunner } from "typeorm";

export class AddLandingPageBriefs1772597370249 implements MigrationInterface {
    name = 'AddLandingPageBriefs1772597370249'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_refresh_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "import_runs" DROP CONSTRAINT "FK_import_runs_account"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_campaigns_account"`);
        await queryRunner.query(`ALTER TABLE "ad_groups" DROP CONSTRAINT "FK_ad_groups_account"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "FK_ads_account"`);
        await queryRunner.query(`ALTER TABLE "keywords" DROP CONSTRAINT "FK_keywords_account"`);
        await queryRunner.query(`ALTER TABLE "search_terms" DROP CONSTRAINT "FK_search_terms_account"`);
        await queryRunner.query(`ALTER TABLE "negative_keywords" DROP CONSTRAINT "FK_negative_keywords_account"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_assets_account"`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" DROP CONSTRAINT "FK_conversion_actions_account"`);
        await queryRunner.query(`ALTER TABLE "geo_performance" DROP CONSTRAINT "FK_geo_performance_account"`);
        await queryRunner.query(`ALTER TABLE "device_performance" DROP CONSTRAINT "FK_device_performance_account"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_change_sets_account"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_change_sets_audit"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_change_sets_created_by"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_decisions_account"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_decisions_audit"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_decisions_change_set"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_decisions_created_by"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_audits_account"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_audits_created_by"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP CONSTRAINT "FK_google_ads_accounts_created_by"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_modifications_account"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_modifications_created_by"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_modifications_approved_by"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "user_accounts" DROP CONSTRAINT "FK_user_accounts_account"`);
        await queryRunner.query(`ALTER TABLE "user_accounts" DROP CONSTRAINT "FK_user_accounts_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_modifications_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_modifications_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_modifications_account_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_modifications_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_email_otps_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_email_otps_email_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_issues_accountId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_issues_accountId_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_issues_accountId_runId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_issues_accountId_severity"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "UQ_campaigns"`);
        await queryRunner.query(`ALTER TABLE "ad_groups" DROP CONSTRAINT "UQ_ad_groups"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "UQ_ads"`);
        await queryRunner.query(`ALTER TABLE "keywords" DROP CONSTRAINT "UQ_keywords"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "UQ_assets"`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" DROP CONSTRAINT "UQ_conversion_actions"`);
        await queryRunner.query(`ALTER TABLE "geo_performance" DROP CONSTRAINT "UQ_geo_performance"`);
        await queryRunner.query(`ALTER TABLE "device_performance" DROP CONSTRAINT "UQ_device_performance"`);
        await queryRunner.query(`ALTER TABLE "import_chunks" DROP CONSTRAINT "UQ_import_chunks"`);
        await queryRunner.query(`CREATE TABLE "run_kpi_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "run_id" character varying(100) NOT NULL, "import_run_id" uuid NOT NULL, "cost" double precision NOT NULL DEFAULT '0', "conversions" double precision NOT NULL DEFAULT '0', "conversions_value" double precision NOT NULL DEFAULT '0', "impressions" bigint NOT NULL DEFAULT '0', "clicks" bigint NOT NULL DEFAULT '0', "ctr" double precision NOT NULL DEFAULT '0', "cpa" double precision NOT NULL DEFAULT '0', "roas" double precision NOT NULL DEFAULT '0', "avg_quality_score" double precision, "active_campaigns" integer NOT NULL DEFAULT '0', "health_score" integer, "snapshot_date" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5535658d0b6eed8b7b805bd76ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c3e219b73f575ec65fa043766" ON "run_kpi_snapshots" ("account_id", "snapshot_date") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "value" text, "description" text, "is_encrypted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."landing_page_briefs_status_enum" AS ENUM('draft', 'completed')`);
        await queryRunner.query(`CREATE TABLE "landing_page_briefs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "source_url" character varying(2048), "primary_keyword" character varying(500), "keyword_cluster" jsonb, "scraped_content" jsonb, "brief" jsonb, "status" "public"."landing_page_briefs_status_enum" NOT NULL DEFAULT 'draft', "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9d9800d1e6405a27465096880a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_report_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "role" character varying(10) NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5a93ef4430c70f694595a92fd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_67dbfe048888978a7236be63b1" ON "audit_report_messages" ("report_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "audit_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "content" text, "status" character varying(20) NOT NULL DEFAULT 'generating', "generated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "duration_ms" integer, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f01b07a42c31f9273ac35cf9b81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f41defe226f66f6cf276ce6bc5" ON "audit_reports" ("account_id", "generated_at") `);
        await queryRunner.query(`CREATE TABLE "ai_analysis_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "triggered_by_id" uuid, "trigger_type" character varying(20) NOT NULL DEFAULT 'manual', "modules_analyzed" text, "total_recommendations" integer NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'running', "started_at" TIMESTAMP WITH TIME ZONE NOT NULL, "completed_at" TIMESTAMP WITH TIME ZONE, "duration_ms" integer, "error_message" text, "module_results" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a7d78c9cb8e95c42bd4a5eb42ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33166d32ec92d2959e816c37ea" ON "ai_analysis_logs" ("account_id", "started_at") `);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD "schedule_enabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD "schedule_days" integer array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD "schedule_time" character varying(5) NOT NULL DEFAULT '07:00'`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD "schedule_frequency" character varying(10) NOT NULL DEFAULT 'weekly'`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD "priority" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD "entity_level" smallint`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD "entity_id" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "acknowledgedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "acknowledgedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "resolvedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "resolvedAt" TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "IDX_123baa002ab017ac4f1e224775" ON "email_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4c245dd70aebeaaf5cf1c0300" ON "email_otps" ("email", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d93358c69085bf842716e996c8" ON "audit_issues" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13b49170d8b473f1d791d8b2d5" ON "audit_issues" ("accountId", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_0991cf9609b13f7b246d0dd182" ON "audit_issues" ("accountId", "severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbad429a64ff207f45e23f4235" ON "audit_issues" ("accountId", "runId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6711686e2dc4fcf9c7c83b8373" ON "user_accounts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6163d54dc1cb367fc0361128bc" ON "user_accounts" ("account_id") `);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "UQ_616faa54945b761f2beb96f9e02" UNIQUE ("account_id", "run_id", "campaign_id")`);
        await queryRunner.query(`ALTER TABLE "ad_groups" ADD CONSTRAINT "UQ_e43f208f7eeb13141769eb64ef4" UNIQUE ("account_id", "run_id", "ad_group_id")`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "UQ_3980cce24f91f4ea90f146cdf7b" UNIQUE ("account_id", "run_id", "ad_id")`);
        await queryRunner.query(`ALTER TABLE "keywords" ADD CONSTRAINT "UQ_5d76c7c47a9dae4f540f864eea7" UNIQUE ("account_id", "run_id", "keyword_id")`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "UQ_fb3e96ea20ef6b8298e4cadd294" UNIQUE ("account_id", "run_id", "asset_id")`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" ADD CONSTRAINT "UQ_2cb4d3c73cfcd3c01834c87f1e4" UNIQUE ("account_id", "run_id", "conversion_action_id")`);
        await queryRunner.query(`ALTER TABLE "geo_performance" ADD CONSTRAINT "UQ_0d83c726c1f27a5a788f0ec7883" UNIQUE ("account_id", "run_id", "campaign_id", "location_id")`);
        await queryRunner.query(`ALTER TABLE "device_performance" ADD CONSTRAINT "UQ_819e9cfc0eaa59fdc5f632d7167" UNIQUE ("account_id", "run_id", "campaign_id", "device")`);
        await queryRunner.query(`ALTER TABLE "import_chunks" ADD CONSTRAINT "UQ_d2fcd17f2cce9fbe793fad8f6f2" UNIQUE ("run_id", "dataset_name", "chunk_index")`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_runs" ADD CONSTRAINT "FK_dcafe2d2149204754ede4e0ada7" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_6fca73bc027c168f88c54e2f112" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_groups" ADD CONSTRAINT "FK_64cd74dd3959c94205dbbf713b5" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "FK_a00cdb6f1c979cf60d7f9fa97f2" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keywords" ADD CONSTRAINT "FK_315046aa043c7ced5c05d171849" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_terms" ADD CONSTRAINT "FK_368f858e4e425694ebcca1b3c56" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "negative_keywords" ADD CONSTRAINT "FK_df12311384efdb0389d4ddaccef" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_f3fd44d69f00473e08a716a0a85" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" ADD CONSTRAINT "FK_9e4b724d1392b487e42ef8cf297" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geo_performance" ADD CONSTRAINT "FK_3dcb6a403c33e127961da5424ab" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_performance" ADD CONSTRAINT "FK_3692017fc9505e3791d5314e1e0" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_7cc9fec1bfb347f9798b6e2363f" FOREIGN KEY ("audit_id") REFERENCES "audits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_0fea1d58f20a436da6725f37788" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_6c5dc76853140c93da1037e6505" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_368fe8c4979f3d606e68bc1e295" FOREIGN KEY ("audit_id") REFERENCES "audits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_1a2045e5d9c4d83992571a53d1c" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_6279a062c125f4306beddce1d03" FOREIGN KEY ("change_set_id") REFERENCES "change_sets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_08c18bc85b0394e06c0d86b393f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_66742a7511667d6eb69f6e08526" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_e9571c8f3ce0cb87d4a94c434af" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD CONSTRAINT "FK_1b8307a5b04dedaa1d7d7b843ab" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "run_kpi_snapshots" ADD CONSTRAINT "FK_8f70730730a4122a50cfdd94468" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_75e1bc69e89d9308596fa898ad4" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_fba906924643d3c1edf2b35b493" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_4f15118a05baa95b199637f82ca" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "landing_page_briefs" ADD CONSTRAINT "FK_cfb3c9b8d021a7cf0e5155306c4" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_report_messages" ADD CONSTRAINT "FK_a0270aa7c5ae3993c3295c72e79" FOREIGN KEY ("report_id") REFERENCES "audit_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_reports" ADD CONSTRAINT "FK_c172a6576af832721bcef47be15" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_analysis_logs" ADD CONSTRAINT "FK_82f7c1f611ed482e1230601f17e" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_analysis_logs" ADD CONSTRAINT "FK_0475dc5fea04d7a2db1885491a6" FOREIGN KEY ("triggered_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_accounts" ADD CONSTRAINT "FK_6711686e2dc4fcf9c7c83b83735" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_accounts" ADD CONSTRAINT "FK_6163d54dc1cb367fc0361128bcd" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_accounts" DROP CONSTRAINT "FK_6163d54dc1cb367fc0361128bcd"`);
        await queryRunner.query(`ALTER TABLE "user_accounts" DROP CONSTRAINT "FK_6711686e2dc4fcf9c7c83b83735"`);
        await queryRunner.query(`ALTER TABLE "ai_analysis_logs" DROP CONSTRAINT "FK_0475dc5fea04d7a2db1885491a6"`);
        await queryRunner.query(`ALTER TABLE "ai_analysis_logs" DROP CONSTRAINT "FK_82f7c1f611ed482e1230601f17e"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "audit_reports" DROP CONSTRAINT "FK_c172a6576af832721bcef47be15"`);
        await queryRunner.query(`ALTER TABLE "audit_report_messages" DROP CONSTRAINT "FK_a0270aa7c5ae3993c3295c72e79"`);
        await queryRunner.query(`ALTER TABLE "landing_page_briefs" DROP CONSTRAINT "FK_cfb3c9b8d021a7cf0e5155306c4"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_4f15118a05baa95b199637f82ca"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_fba906924643d3c1edf2b35b493"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP CONSTRAINT "FK_75e1bc69e89d9308596fa898ad4"`);
        await queryRunner.query(`ALTER TABLE "run_kpi_snapshots" DROP CONSTRAINT "FK_8f70730730a4122a50cfdd94468"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP CONSTRAINT "FK_1b8307a5b04dedaa1d7d7b843ab"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_e9571c8f3ce0cb87d4a94c434af"`);
        await queryRunner.query(`ALTER TABLE "audits" DROP CONSTRAINT "FK_66742a7511667d6eb69f6e08526"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_08c18bc85b0394e06c0d86b393f"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_6279a062c125f4306beddce1d03"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_1a2045e5d9c4d83992571a53d1c"`);
        await queryRunner.query(`ALTER TABLE "decisions" DROP CONSTRAINT "FK_368fe8c4979f3d606e68bc1e295"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_6c5dc76853140c93da1037e6505"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_0fea1d58f20a436da6725f37788"`);
        await queryRunner.query(`ALTER TABLE "change_sets" DROP CONSTRAINT "FK_7cc9fec1bfb347f9798b6e2363f"`);
        await queryRunner.query(`ALTER TABLE "device_performance" DROP CONSTRAINT "FK_3692017fc9505e3791d5314e1e0"`);
        await queryRunner.query(`ALTER TABLE "geo_performance" DROP CONSTRAINT "FK_3dcb6a403c33e127961da5424ab"`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" DROP CONSTRAINT "FK_9e4b724d1392b487e42ef8cf297"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_f3fd44d69f00473e08a716a0a85"`);
        await queryRunner.query(`ALTER TABLE "negative_keywords" DROP CONSTRAINT "FK_df12311384efdb0389d4ddaccef"`);
        await queryRunner.query(`ALTER TABLE "search_terms" DROP CONSTRAINT "FK_368f858e4e425694ebcca1b3c56"`);
        await queryRunner.query(`ALTER TABLE "keywords" DROP CONSTRAINT "FK_315046aa043c7ced5c05d171849"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "FK_a00cdb6f1c979cf60d7f9fa97f2"`);
        await queryRunner.query(`ALTER TABLE "ad_groups" DROP CONSTRAINT "FK_64cd74dd3959c94205dbbf713b5"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_6fca73bc027c168f88c54e2f112"`);
        await queryRunner.query(`ALTER TABLE "import_runs" DROP CONSTRAINT "FK_dcafe2d2149204754ede4e0ada7"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "import_chunks" DROP CONSTRAINT "UQ_d2fcd17f2cce9fbe793fad8f6f2"`);
        await queryRunner.query(`ALTER TABLE "device_performance" DROP CONSTRAINT "UQ_819e9cfc0eaa59fdc5f632d7167"`);
        await queryRunner.query(`ALTER TABLE "geo_performance" DROP CONSTRAINT "UQ_0d83c726c1f27a5a788f0ec7883"`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" DROP CONSTRAINT "UQ_2cb4d3c73cfcd3c01834c87f1e4"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "UQ_fb3e96ea20ef6b8298e4cadd294"`);
        await queryRunner.query(`ALTER TABLE "keywords" DROP CONSTRAINT "UQ_5d76c7c47a9dae4f540f864eea7"`);
        await queryRunner.query(`ALTER TABLE "ads" DROP CONSTRAINT "UQ_3980cce24f91f4ea90f146cdf7b"`);
        await queryRunner.query(`ALTER TABLE "ad_groups" DROP CONSTRAINT "UQ_e43f208f7eeb13141769eb64ef4"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "UQ_616faa54945b761f2beb96f9e02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6163d54dc1cb367fc0361128bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6711686e2dc4fcf9c7c83b8373"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbad429a64ff207f45e23f4235"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0991cf9609b13f7b246d0dd182"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13b49170d8b473f1d791d8b2d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93358c69085bf842716e996c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4c245dd70aebeaaf5cf1c0300"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_123baa002ab017ac4f1e224775"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "resolvedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "resolvedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "acknowledgedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "acknowledgedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_issues" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_issues" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD "entity_id" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP COLUMN "entity_level"`);
        await queryRunner.query(`ALTER TABLE "modifications" DROP COLUMN "priority"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP COLUMN "schedule_frequency"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP COLUMN "schedule_time"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP COLUMN "schedule_days"`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" DROP COLUMN "schedule_enabled"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33166d32ec92d2959e816c37ea"`);
        await queryRunner.query(`DROP TABLE "ai_analysis_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f41defe226f66f6cf276ce6bc5"`);
        await queryRunner.query(`DROP TABLE "audit_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67dbfe048888978a7236be63b1"`);
        await queryRunner.query(`DROP TABLE "audit_report_messages"`);
        await queryRunner.query(`DROP TABLE "landing_page_briefs"`);
        await queryRunner.query(`DROP TYPE "public"."landing_page_briefs_status_enum"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c3e219b73f575ec65fa043766"`);
        await queryRunner.query(`DROP TABLE "run_kpi_snapshots"`);
        await queryRunner.query(`ALTER TABLE "import_chunks" ADD CONSTRAINT "UQ_import_chunks" UNIQUE ("run_id", "dataset_name", "chunk_index")`);
        await queryRunner.query(`ALTER TABLE "device_performance" ADD CONSTRAINT "UQ_device_performance" UNIQUE ("account_id", "run_id", "campaign_id", "device")`);
        await queryRunner.query(`ALTER TABLE "geo_performance" ADD CONSTRAINT "UQ_geo_performance" UNIQUE ("account_id", "run_id", "campaign_id", "location_id")`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" ADD CONSTRAINT "UQ_conversion_actions" UNIQUE ("account_id", "run_id", "conversion_action_id")`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "UQ_assets" UNIQUE ("account_id", "run_id", "asset_id")`);
        await queryRunner.query(`ALTER TABLE "keywords" ADD CONSTRAINT "UQ_keywords" UNIQUE ("account_id", "run_id", "keyword_id")`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "UQ_ads" UNIQUE ("account_id", "run_id", "ad_id")`);
        await queryRunner.query(`ALTER TABLE "ad_groups" ADD CONSTRAINT "UQ_ad_groups" UNIQUE ("account_id", "run_id", "ad_group_id")`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "UQ_campaigns" UNIQUE ("account_id", "run_id", "campaign_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_issues_accountId_severity" ON "audit_issues" ("accountId", "severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_issues_accountId_runId" ON "audit_issues" ("accountId", "runId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_issues_accountId_category" ON "audit_issues" ("accountId", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_issues_accountId" ON "audit_issues" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_otps_email_expires_at" ON "email_otps" ("email", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_email_otps_email" ON "email_otps" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_modifications_entity" ON "modifications" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_modifications_account_status" ON "modifications" ("account_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_modifications_status" ON "modifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_modifications_account_id" ON "modifications" ("account_id") `);
        await queryRunner.query(`ALTER TABLE "user_accounts" ADD CONSTRAINT "FK_user_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_accounts" ADD CONSTRAINT "FK_user_accounts_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_audit_logs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_modifications_approved_by" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_modifications_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifications" ADD CONSTRAINT "FK_modifications_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "google_ads_accounts" ADD CONSTRAINT "FK_google_ads_accounts_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_audits_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audits" ADD CONSTRAINT "FK_audits_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_decisions_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_decisions_change_set" FOREIGN KEY ("change_set_id") REFERENCES "change_sets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_decisions_audit" FOREIGN KEY ("audit_id") REFERENCES "audits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decisions" ADD CONSTRAINT "FK_decisions_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_change_sets_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_change_sets_audit" FOREIGN KEY ("audit_id") REFERENCES "audits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "change_sets" ADD CONSTRAINT "FK_change_sets_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_performance" ADD CONSTRAINT "FK_device_performance_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geo_performance" ADD CONSTRAINT "FK_geo_performance_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversion_actions" ADD CONSTRAINT "FK_conversion_actions_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_assets_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "negative_keywords" ADD CONSTRAINT "FK_negative_keywords_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_terms" ADD CONSTRAINT "FK_search_terms_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keywords" ADD CONSTRAINT "FK_keywords_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ads" ADD CONSTRAINT "FK_ads_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_groups" ADD CONSTRAINT "FK_ad_groups_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_campaigns_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_runs" ADD CONSTRAINT "FK_import_runs_account" FOREIGN KEY ("account_id") REFERENCES "google_ads_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_refresh_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
